from pathlib import Path
import shutil

import typer
import uvicorn

from raglift.config import write_default_config
from raglift.graph import RAGGraph

app = typer.Typer(help="Build full-stack LangGraph RAG apps without rebuilding the plumbing.")


@app.command()
def init(name: str) -> None:
    target = Path(name)
    target.mkdir(parents=True, exist_ok=True)
    (target / "docs").mkdir(exist_ok=True)
    write_default_config(target / "raglift.toml")
    (target / ".env.example").write_text("OPENAI_API_KEY=sk-your-key\n", encoding="utf-8")
    (target / "README.md").write_text(f"# {name}\n\nGenerated by RagLift.\n", encoding="utf-8")
    typer.echo(f"Initialized {target}")


@app.command()
def ingest(path: str, config: str = "raglift.toml") -> None:
    ids = RAGGraph.from_config(config).ingest(path)
    typer.echo(f"Ingested {len(ids)} chunks")


@app.command()
def ask(question: str, config: str = "raglift.toml") -> None:
    answer = RAGGraph.from_config(config).ask(question)
    typer.echo(answer.text)
    for source in answer.sources:
        typer.echo(f"- {source.path}#{source.chunk_id}")


@app.command()
def serve(host: str = "0.0.0.0", port: int = 8000) -> None:
    uvicorn.run("raglift.server:app", host=host, port=port, reload=False)


@app.command()
def create(
    name: str,
    frontend: str = typer.Option("angular"),
    backend: str = typer.Option("fastapi"),
) -> None:
    if frontend != "angular" or backend != "fastapi":
        raise typer.BadParameter("v0.1 only supports --frontend angular --backend fastapi")
    src = Path(__file__).resolve().parent.parent / "templates" / "fastapi-angular"
    shutil.copytree(src, Path(name), dirs_exist_ok=True)
    typer.echo(f"Created full-stack app at {name}")


if __name__ == "__main__":
    app()
